language: node_js

sudo: required
dist: trusty

node_js:
  - "6"

addons:
  firefox: latest-esr

env: DISPLAY=":99.0" IN_TRAVIS="1" GOPATH="${HOME}/go"

install:
  - sudo apt-get update
  - sudo apt-get install -qq libotr5-dev rng-tools
  - npm install
  - mkdir -p $GOPATH/src/github.com/coniks-sys
  - pushd $GOPATH/src/github.com/coniks-sys
  - git clone https://github.com/coniks-sys/coniks-go.git
  - pushd coniks-go
  - git checkout 90075472
  - pushd client/cgo
  - go get .
  - popd
  - popd
  - popd

before_script:
  - sudo rm -f /dev/random
  - sudo mknod -m 0666 /dev/random c 1 9
  - echo HRNGDEVICE=/dev/urandom | sudo tee /etc/default/rng-tools
  - sudo /etc/init.d/rng-tools restart
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - pushd $GOPATH/src/github.com/coniks-sys/coniks-go/client/cgo
  - make
  - cp libconiks.so $HOME/build/arlolra/ctypes-otr/addon
  - popd

script:
  - npm run lint
  - npm run jpm-travis
